name: LFS init
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: lfs-init
  cancel-in-progress: true

env:
  MAIN_TEMPLATE: "SublimationApp/sublimationapp.github.io"

jobs:
  check-lfs:
    if: github.repository != env.MAIN_TEMPLATE
    runs-on: ubuntu-latest
    outputs:
      lfs_configured: ${{ steps.check.outputs.lfs_configured }}

    steps:
    - uses: actions/checkout@v6

    - name: Check if LFS is configured
      id: check
      run: |
        # Look for 'filter=lfs' in .gitattributes
        if [ -f .gitattributes ] && grep -q "filter=lfs" .gitattributes; then
          echo "lfs_configured=true" >> $GITHUB_OUTPUT
        else
          echo "lfs_configured=false" >> $GITHUB_OUTPUT
        fi

  enable-lfs:
    runs-on: ubuntu-latest
    needs: [check-lfs]
    if: needs.check-lfs.outputs.lfs_configured == 'false'

    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Ensure write permissions
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # 3. Fetch and merge template
    - name: Initialize and Track
      run: |
        git lfs install
        git lfs track "*.zip"
        # Important: .gitattributes must be added first
        git add .gitattributes
        git commit -m "LFS init implemented"
        git push origin main